name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Changing file permissions
        run: chmod 755 file_sub.py
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
          # run: |
          # echo "Changing file permissions"
          # chmod 755 file_sub.py
          # echo "Changing PDF name"
          # python ./file_sub.py -f main.pdf -e project
          # echo "Uploading to GitHub"
          # git add Adebayo_Braimah_115099306_project.pdf
          # git commit -m "[skip actions] Auto WF: Document upload"
          # git push origin main
